#!/bin/bash
docker run -ti --rm \
-v $(pwd):/myApp:rw \
-w /myApp \
beevelop/ionic \
bash -c " \
    rm -rf android && \
    rm -rf build && \
    ionic build --prod && \
    ionic capacitor build android && \
    yes | /opt/android/tools/bin/sdkmanager --update && \
    yes | /opt/android/tools/bin/sdkmanager --licenses && \
    cd android && \
    ./gradlew assembleDebug && \
    mkdir -p APK && \
    cp android/app/build/outputs/apk/debug/app-debug.apk APK/app-debug.apk \
"
