#!/bin/bash
rm -rf android &&
rm -rf build &&
npm install &&
npm run build --prod &&
ionic capacitor add android &&
npm run resources &&
docker run -ti --rm \
-v $(pwd):/myApp:rw \
-w /myApp \
beevelop/ionic \
bash -c "yes | /opt/android/tools/bin/sdkmanager --update;yes | /opt/android/tools/bin/sdkmanager --licenses;cd android;./gradlew assembleDebug"
